#ddev-generated
services:
  basex:
    container_name: ddev-${DDEV_SITENAME}-basex
    image: quodatum/basexhttp:latest
    restart: "no"
    ports:
      - "9984:8080"
    volumes:
      - basex-data:/srv/basex/data
      - basex-webapp:/srv/basex/webapp
      - basex-repo:/srv/basex/repo
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
    environment:
      - VIRTUAL_HOST=$DDEV_HOSTNAME
      - HTTP_EXPOSE=9984:8080
      - HTTPS_EXPOSE=9984:8080
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 2s
      timeout: 5s
      retries: 30
      start_period: 10s

volumes:
  basex-data:
  basex-webapp:
  basex-repo: